"""rename department

Revision ID: 60f73850b68c
Revises: 4e324203e5b5
Create Date: 2025-06-11 13:16:18.965790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f73850b68c'
down_revision = '4e324203e5b5'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('department', 'departments')


def downgrade():
    op.rename_table('departments', 'department')
# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
